config/routes.rb
Rails.application.routes.draw do

  root to: 'page#index'
  post 'contactUS', to: 'page#contactUS'
  devise_scope :user do
    get "/sign_up",  :to => "page#index"
  end
  resources :sender do
    resources :images, only: [:new,:create,:edit,:update]
    collection do
      post "senderByPage", :senderByPage
      post "senderAll", :senderAll
      post "sendTopic", :sendTopic
      get "sender", :sender
    end
  end
  resources :images, only: [:show,:index,:destroy] do
    collection do
      post 'sendScreenshot', :sendScreenshot
      post 'createAndSend',  :createAndSend, :defaults => {:format => 'json'}
    end
  end
  devise_for :users, :path=> '', :path_names =>{:sign_in => 'signin',:sign_out=>'signout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/sender_controller.rb
require 'fcm'
require "retries"
class SenderController < ApplicationController
  before_action :authenticate_user!, only:[:destroy]
  before_action :set_token, only: [:show,:edit,:update,:destroy]
  def index
    @tokens =  Token.all.paginate(:page => params[:page],:per_page => 10).order("created_at ASC")
    @page ||= params[:page]
    @page = 1
  end
  def show
  end
  def destroy
    @token.destroy
    respond_to do |format|
      format.html {redirect_to sender_index_path, notice: "The token was destroyed"}
      format.json {render json: @token, status: 204}
    end
  end
  def new
    @token = Token.new
  end
  def create
    @token = Token.new(tokens_params)
    respond_to do |format|
      if @token.save
        format.html{redirect_to sender_index_path,notice:"The token was created"}
        format.json {render json: @token, status: 201}
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end
  def edit
  end
  def update
    respond_to do |format|
      if @token.update(tokens_params)
        format.html { redirect_to sender_index_path, notice: 'The token was updated' }
        format.json {render json: @token, status: 201}
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end
  def sender
    render 'sendTopic'
  end
  def sendTopic
    respond_to do |format|
      if params.key?("topic")
        response =  nil
        body = params["body"]
        title = params["title"]
        body ||= "The route " + params["topic"] + " just crossed a checkpoint"
        title ||= "Checkpoint notification"

        with_retries(:max_tries=>20,:base_sleep_seconds=>0.1,:max_sleep_seconds=>2.0) do |attempt|
          if attempt == 20
            format.html {redirect_to sender_index_path, notice: 'There was an error'}
            format.json {render json: {error: "There was an error"}, status:500}
          else
            response ||= sendMessageToTopic(params["topic"],body,title)
            format.html {redirect_to sender_index_path, notice: 'The message was sent succesfully'}
            format.json {render json: {success:"The message was sent succesfully"}, status:200}
          end
        end
      else
        format.html {redirect_to sender_index_path, notice: "We can\'t send the message"}
        format.json {render json: {error: "We can\'t send the message"}, status:400}
      end
    end
  end
  def senderAll
    tokens = Token.all
    respond_to do |format|
      response = nil
      body = params["body"]
      title = params["title"]
      body ||= "The route just crossed a checkpoint"
      title ||= "Checkpoint notification"
      with_retries(:max_tries=> 20,:base_sleep_seconds =>0.1, :max_sleep_seconds => 2.0)  do |attempt|
        if attempt == 20
          format.html {redirect_to sender_index_path, notice: 'There was an error'}
          format.json {render json: {error: "There was an error"}, status:500}
        else
          response ||= sendMessage(tokens,body,title)
          format.html {redirect_to sender_index_path, notice: 'The message was sent succesfully'}
          format.json {render json: {success: "The message was sent succesfully"}, status:200}
        end
      end
    end

  end
  def senderByPage
    tokens = Token.all.paginate(:page => params[:page],:per_page => 10).order("created_at ASC")
    respond_to do |format|
      response = nil
      body = params["body"]
      title = params["title"]
      body ||= "The route just crossed a checkpoint"
      title ||= "Checkpoint notification"
      with_retries(:max_tries=> 20,:base_sleep_seconds =>0.1, :max_sleep_seconds => 2.0) do |attempt|
        if attempt == 20
          format.html {redirect_to sender_index_path, notice: 'The message was sent succesfully'}
          format.json {render json: {error:"There was an error"}, status:500}
        else
          response ||= sendMessage(tokens,body,title)
          format.html {redirect_to sender_index_path, notice: 'The message was sent succesfully'}
          format.json {render json: {success:"The message was sent succesfully"}, status:200}
        end
      end
    end
  end

  private
    def sendMessageToTopic(topic,body,title)
      fcm = FCM.new(Rails.application.secrets.fcm_key)
      options = {notification: {body: body,title:title,sound:"default"},priority:"high",content_available:true,time_to_live:2419200}
      response = fcm.send_to_topic(topic,options)
      unless response[:status_code] >= 200 && response[:status_code] < 300
        raise StandardError,"Error"
      end
    end
    def sendMessage(tokens,body,title)
      fcm = FCM.new(Rails.application.secrets.fcm_key)
      registration_ids = []
      tokens.each do |t|
        registration_ids << t.token_id
      end
      options = {notification: {body: body,title:title},priority:"high",content_available:true,time_to_live:2419200}
      response = fcm.send(registration_ids,options)
      if response[:status_code] >= 200 && response[:status_code] < 300
        deleteInvalidTokens(response,registration_ids)
      else
        raise StandardError,"Error"
      end
      response
    end
    def deleteInvalidTokens(response,registration_ids )
      body = response[:body]
      parsed_json = JSON(body)
      results = parsed_json["results"]
      results.each_with_index do |val,index|
        #resultValue = parsed_json = JSON(val)
        if val.key?("error")
          if val["error"] == "InvalidRegistration" || val["error"] == "NotRegistered"
            token_id = registration_ids[index]
            t = Token.where("token_id = ?",token_id).first
            t.destroy
          end
        end
      end
    end
    def set_token
      @token = Token.find(params[:id])
    end
    def tokens_params
      params.require(:token).permit(:token_id)
    end
end

app/helpers/sender_helper.rb
module SenderHelper
end

app/views/sender/_form.html.erb
<%= form_for @token, url: {controller:"sender",action: "create"} do |f| %>
  <% if @token.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade-in" id="alert-app" role="alert">
      <button type="button" class="close" aria-label="Close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :token_id,:for=>"tokenField" %>
    <%= f.text_field :token_id, :id=>"tokenField",:class=>"form-control" %>
  </div>
  <%= f.submit "Add", :class=>"btn btn-success"%>

<% end %>

app/views/sender/_formUpdate.html.erb
<%= form_for @token, url: {controller:"sender",action: "update"} do |f| %>
  <% if @token.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade-in" id="alert-app" role="alert">
      <button type="button" class="close" aria-label="Close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :token_id,:for=>"tokenField" %>
    <%= f.text_field :token_id, :id=>"tokenField",:class=>"form-control" %>
  </div>
  <%= f.submit "Update", :class=>"btn btn-success"%>

<% end %>

app/views/sender/_paginate.html.erb
<%= will_paginate @tokens, renderer: BootstrapPagination::Rails %>

app/views/sender/_tokenImages.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4">
  <img src="<%=image.image.thumb.url %>" width="150" height="150" class="img-responsive img-thumbnail">
  <h3>Route</h3>
  <p><%= image.route %></p>
  <%=link_to 'Show',image, :class=>"btn btn-primary" %>
  <%=link_to 'Edit',edit_sender_image_path(@token,image), :class=>"btn btn-success" %>
  <%= link_to 'Destroy',image_path(image), :class=>"btn btn-danger",data: { confirm: "Are you sure?" }, method: :delete %>
</div>

app/views/sender/_tokens.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="col-md-6">Token ID</th>
        <th class="col-md-6">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @tokens.each do |token| %>
        <tr>
          <td class="col-md-6"><%= token.token_id %></td>
          <td class="col-md-6">
            <div class="col-xs-12 col-sm-12 col-lg-12">
              <%= link_to 'Show',sender_path(token), :class=>"btn btn-primary" %>
            </div>
            <div class="col-xs-12 col-sm-12 col-lg-12">
              <%= link_to 'Destroy',sender_path(token), :class=>"btn btn-danger",data: { confirm: "Are you sure?" }, method: :delete %>
            </div>
            <div class="col-xs-12 col-sm-12 col-lg-12">
              <%= link_to 'Update',edit_sender_path(token),:class=>"btn btn-success" %>
            </div>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/sender/edit.html.erb
<div class="page-header">
  <h2>Edit</h2>
</div>
<%= render 'formUpdate' %>
<%= link_to 'back', sender_index_path, :class=>"btn btn-default" %>

app/views/sender/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Add', new_sender_path, :class=>"btn btn-success" %>
    <%= link_to "Send message topic", sender_sender_index_path, :class=>"btn btn-primary" %>

  </div>
  <h2>Tokens</h2>
</div>
<% unless @tokens.empty? %>
  <div id="tokens">
    <%= render 'tokens' %>
  </div>
  <div id="paginate">
    <%= render 'paginate' %>
  </div>
  <div class="row">
    <div class="col-xs-4 col-lg-2">
      <%=button_to "Send page", {:controller=>"sender",:action=>"senderByPage", :page=>@page},{:class=> 'btn btn-default'} %>
    </div>
    <div class="col-xs-4 col-lg-2">
      <%=button_to "Send All",  {:controller=>"sender",:action=>"senderAll",:page=>@page}, {:class=> 'btn btn-primary'} %>
    </div>
  </div>


<% end %>

app/views/sender/new.html.erb
<div class="page-header">
  <h2>New</h2>
</div>
<%= render 'form'%>
<%= link_to 'back', sender_index_path, :class=>"btn btn-default" %>

app/views/sender/sendTopic.html.erb
<div class="page-header">
  <h2>Send message to Topic</h2>
</div>
<%= form_tag(controller: "sender",action:"sendTopic",method:"post") do %>
  <div class="form-group">
    <%= label_tag :topic, nil, {for: "topicField"} %>
    <%= text_field_tag :topic, nil, placeholder: 'Enter the name of the topic...', class:"form-control", id:"topicField" %>
  </div>
  <%= submit_tag "Send", {class:"btn btn-success"} %>


<% end %>

app/views/sender/show.html.erb
<div class="page-header">
  <h2>Details</h2>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <tbody>
      <tr>
        <th>ID</th>
        <th><%= @token.token_id %></th>
      </tr>
      <tr>
        <th>Created at</th>
        <th><%= @token.created_at %></th>
      </tr>
      <tr>
        <th>Updated at</th>
        <th><%= @token.updated_at %></th>
      </tr>
    </tbody>
  </table>
</div>
<% unless @token.images.empty? %>
  <div class="tokenImages">
    <div class="row">
      <%= render :partial => 'tokenImages', :collection=> @token.images,:as => :image %>
    </div>
  </div>
<% end %>
<br>
<br>
<%= link_to 'new screenshot', new_sender_image_path(@token), :class=>"btn btn-success" %>
<%= link_to 'back', sender_index_path, :class=>"btn btn-default" %>