config/routes.rb
Rails.application.routes.draw do

  root to: 'page#index'
  post 'contactUS', to: 'page#contactUS'
  devise_scope :user do
    get "/sign_up",  :to => "page#index"
  end
  resources :sender do
    resources :images, only: [:new,:create,:edit,:update]
    collection do
      post "senderByPage", :senderByPage
      post "senderAll", :senderAll
      post "sendTopic", :sendTopic
      get "sender", :sender
    end
  end
  resources :images, only: [:show,:index,:destroy] do
    collection do
      post 'sendScreenshot', :sendScreenshot
      post 'createAndSend',  :createAndSend, :defaults => {:format => 'json'}
    end
  end
  devise_for :users, :path=> '', :path_names =>{:sign_in => 'signin',:sign_out=>'signout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, :presence=>true
  validates :route, :presence=>true
  belongs_to :token
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all.paginate(:page => params[:page],:per_page=> 10).order("created_at ASC")
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @imageTemp = Image.where("token_id = ? AND route = ?",params[:sender_id],params[:image][:route]).first
    if @imageTemp == nil
      @image = Image.new(image_params)
      @token = Token.find(params[:sender_id])
      respond_to do |format|
        if @image.save
          @token.images << @image
          @token.save
          format.html { redirect_to @image, notice: 'Image was successfully created.' }
          format.json { render @image, status: 201 }
        else
          format.html { render :new }
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
    else
      if @imageTemp.update(image_params)
        format.html { redirect_to @imageTemp, notice: 'Image was successfully updated.' }
        format.json { render :show, status: 201}
      else
        format.html { render :edit }
        format.json { rendroer json: @imageTemp.errors, status: :unprocessable_entity }
      end
    end
  end
  def createAndSend
    if params.key?("file") && params.key?("token_id") && params.key?("route")
      token =  Token.where("token_id = ?",params[:token_id]).first
      imageTemp = Image.where("token_id = ? AND route = ?",token.id,params[:route]).first
      if imageTemp == nil
        image = Image.new(image:params[:file],route: params[:route])
        if image.save
          token.images << image
          token.save
          imageThumbUrl = image.image.thumb.url
          imageUrl = image.image.url
          sendMessageFromClient(params[:token_id],params[:route],imageThumbUrl,imageUrl)
        else
          render json: {errors: "There was an error"}, status: 500
        end
      else

        if imageTemp.update(image:params[:file])
          imageThumbUrl = imageTemp.image.thumb.url
          imageUrl = imageTemp.image.url
          sendMessageFromClient(params[:token_id],params[:route],imageThumbUrl,imageUrl)
        else
          render json: {errors: "There was an error"}, status: 500
        end
      end
    else
      render json: {errors: "Some parameters are missing"}, status: 400
    end

  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: 201}
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { render json: @image, status: 204 }
    end
  end
  def sendScreenshot
    response = nil
    topic = params[:route]
    token = Token.find(params[:token_id])
    token_id = token.token_id
    image = Image.where("token_id = ? AND route = ?",token.id,topic).first
    title = "Screenshot"
    subtitle = "The person with id #{token_id} has just send your location"
    body = "This person is following the route with id #{topic}"
    imageThumbUrl = image.image.thumb.url
    imageUrl = image.image.url
    with_retries(:max_tries=>20,:base_sleep_seconds=>0.1,:max_sleep_seconds=>20) do |attempt|
      if attempt == 20
        redirect_to sender_index_path, notice: 'There was a problem when we tried to send the screenshot'
      else
        reponse ||= sendMessageToTopicWithImage(topic,body,title,subtitle,imageUrl,imageThumbUrl)
        redirect_to sender_index_path, notice: 'The message was sent succesfully'
      end
    end
  end

  private
    def sendMessageFromClient(token_id,topic,imageThumbUrl,imageUrl)
      title = "Screenshot"
      subtitle = "The person with id #{token_id} has just send your location"
      body = "This person is following the route with id #{topic}"
      with_retries(:max_tries=>20,:base_sleep_seconds=>0.1,:max_sleep_seconds=>20) do |attempt|
        if attempt == 20
          render json: {errors: "We can't send the message"}, status: 500
        else
          reponse ||= sendMessageToTopicWithImage(topic,body,title,subtitle,imageUrl,imageThumbUrl)
          render json: {success: "We have sent the message"}, status: 200
        end
      end
    end
    def sendMessageToTopicWithImage(topic,body,title,subtitle,imageUrl,imageThumbUrl)
      fcm = FCM.new(Rails.application.secrets.fcm_key)
      options = {notification: {body: body,title:title,sound:"default",subtitle:subtitle,click_action:"co.edu.unal.agutierrezt.sokol.screenshot"},data:{image_url: imageUrl,image_thumb_url: imageThumbUrl},priority:"high",content_available:true,time_to_live:2419200,collapse_key:"co.edu.unal.agutierrezt.sokol.screenshot"}
      response = fcm.send_to_topic(topic,options)
      unless response[:status_code] >= 200 && response[:status_code] < 300
        raise StandardError,"Error"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image,:route,:token_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, url: sender_images_path do |f| %>
  <% if @image.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade-in" id="alert-app" role="alert">
      <button type="button" class="close" aria-label="Close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :route, :for=>"routeField" %>
    <%= f.text_field :route, :id=>"routeField", :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, :for=>"imageField" %>
    <%= f.file_field :image,  :id=>"imageField" %>
  </div>

  <%= f.submit 'Submit',:class=>"btn btn-success" %>
<% end %>

app/views/images/_images.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4">
  <img src="<%=image.image.thumb.url %>" class="img-responsive img-thumbnail" width="150" height="150">
  <div class="row">
    <br>
    <%= link_to 'Show', image_path(image), :class=>"btn btn-primary" %>
    <%=link_to 'Edit',edit_sender_image_path(image.token,image), :class=>"btn btn-success" %>
    <%= link_to 'Destroy',image_path(image), :class=>"btn btn-danger",data: { confirm: "Are you sure?" }, method: :delete %>
  </div>
  <br>
  <div class="row">
    <%= link_to 'Send screenshot', sendScreenshot_images_path(:token_id => image.token_id,:route=>image.route), :class=>"btn btn-default", method: :post %>
  </div>
</div>

app/views/images/_paginate.html.erb
<%= will_paginate @images, renderer: BootstrapPagination::Rails %>

app/views/images/edit.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Show', @image, :class=>"btn btn-success" %>
    <%= link_to 'All images', images_path, :class=>"btn btn-primary" %>
  </div>
  <h2>Edit image</h2>
</div>

<%= render 'form', image: @image %>

app/views/images/index.html.erb
<div class="page-header">
  <h2>Images</h2>
</div>

<% unless @images.empty? %>
  <div class="images">
    <div class="row">
      <%= render :partial => 'images',  :collection => @images, :as => :image %>
    </div>
  </div>
  <div class="paginate">
    <%= render 'paginate' %>
  </div>
<% end %>

app/views/images/new.html.erb
<div class="page-header">
  <h2>New Image</h2>
</div>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path, :class=>"btn btn-default" %>

app/views/images/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%=link_to 'All Images',    images_path, :class=>"btn btn-success" %>
  </div>
  <h2>Description</h2>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <tbody>
      <tr>
        <th>Route</th>
        <th><%= @image.route %></th>
      </tr>
      <tr>
        <th>Screenshot</th>
        <th><img src="<%=@image.image.url%>" width="300" height="300" class="img-responsive img-thumbnail"></th>
      </tr>
    </tbody>
  </table>
</div>
<br>
<br>

<%=link_to 'Edit',edit_sender_image_path(@image.token,@image), :class=>"btn btn-success" %>
<%= link_to 'Destroy',image_path(@image), :class=>"btn btn-danger",data: { confirm: "Are you sure?" }, method: :delete %>
<br>
<br>
<%= link_to 'Send screenshot', sendScreenshot_images_path(:token_id => @image.token_id,:route=>@image.route), :class=>"btn btn-primary", method: :post %>