config/routes.rb
Rails.application.routes.draw do

  root to: 'page#index'
  post 'contactUS', to: 'page#contactUS'
  devise_scope :user do
    get "/sign_up",  :to => "page#index"
  end
  resources :sender do
    resources :images, only: [:new,:create,:edit,:update]
    collection do
      post "senderByPage", :senderByPage
      post "senderAll", :senderAll
      post "sendTopic", :sendTopic
      get "sender", :sender
    end
  end
  resources :images, only: [:show,:index,:destroy] do
    collection do
      post 'sendScreenshot', :sendScreenshot
      post 'createAndSend',  :createAndSend, :defaults => {:format => 'json'}
    end
  end
  devise_for :users, :path=> '', :path_names =>{:sign_in => 'signin',:sign_out=>'signout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <%= link_to "FCMSOKOL", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
          <li><%=  link_to 'Home', root_path %></a></li>
          <li><a href="#about"> About us</a></li>
          <li><a href="#contact">Contact us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'tokens' ,sender_index_path %></li>
          <li><%= link_to 'images', images_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%=link_to 'profile', edit_user_registration_path %> </li>
              <li><%= link_to  'log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%=link_to 'log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FcmSokol</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <%= render 'layouts/menu' %>

  <div class="container">
    <% flash.each do |key,value| %>
      <div class="alert alert-<%= key %> alert-dismissible fade-in"  id="alert-app" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      </div>
    <% end %>
  </div>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>